// Copyright 2010-2014 RethinkDB, all rights reserved.
#ifndef CLUSTERING_ADMINISTRATION_JOBS_BACKEND_HPP_
#define CLUSTERING_ADMINISTRATION_JOBS_BACKEND_HPP_

#include <memory>
#include <string>
#include <vector>

#include "rdb_protocol/admin_identifier_format.hpp"
#include "rdb_protocol/artificial_table/backend.hpp"

namespace auth {
class user_context_t;
}

class jobs_artificial_table_fdb_backend_t final :
    public artificial_table_fdb_backend_t
{
public:
    explicit jobs_artificial_table_fdb_backend_t(
        admin_identifier_format_t _identifier_format);
    ~jobs_artificial_table_fdb_backend_t();

    std::string get_primary_key_name() const override;

    bool read_all_rows_as_vector(
            FDBDatabase *fdb,
            auth::user_context_t const &user_context,
            const signal_t *interruptor,
            std::vector<ql::datum_t> *rows_out,
            admin_err_t *error_out) override;

    bool read_row(
            FDBTransaction *txn,
            auth::user_context_t const &user_context,
            ql::datum_t primary_key,
            const signal_t *interruptor,
            ql::datum_t *row_out,
            admin_err_t *error_out) override;

    bool write_row(
            FDBTransaction *txn,
            auth::user_context_t const &user_context,
            ql::datum_t primary_key,
            bool pkey_was_autogenerated,
            ql::datum_t *new_value_inout,
            const signal_t *interruptor,
            admin_err_t *error_out) override;

private:
    const admin_identifier_format_t identifier_format;
    DISABLE_COPYING(jobs_artificial_table_fdb_backend_t);
};

// TODO: Would be cool to expose secondary index of jobs by task id.

#endif /* CLUSTERING_ADMINISTRATION_JOBS_BACKEND_HPP_ */
